### ISSUE TITLE
使用主题的疑问

### ISSUE THREAD

**Issue by justforlxz** [ehazon/ehazon.github.io#1]
我将文件复制进主题的文件夹，也修改_config.yml了，但是预览以后发现是hexo的默认主题，但是使用其他主题都正常。

**Comment by Haojen** [comment]
妳好,问题解决了吗?
[另外项目源码地址正准备迁移到 [hexo-theme-anisina](https://github.com/ehazon/hexo-theme-Anisina) ,原项目地址在完成迁移后可能会删除,造成的不便请多包涵 :)

**Comment by justforlxz** [comment]
```
layout/page.ejs:124
    122|     <div class="row">
    123|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">
 >> 124|             <%- body %>
    125|         </div>
    126|     <!-- Sidebar Container -->
    127|             <div class="

body is not defined
```

hexo g的时候提示的错误

**Comment by Haojen** [comment]
可否贴上你的整个未编译的博客代码? 便于我帮你找到问题,另外执行 hexo g 的之前,有无 hexo clean 呢?

**Comment by justforlxz** [comment]
抱歉啦，是我改错配置了，已经没问题了。主题很好看。

**Comment by Haojen** [comment]
多谢你的反馈, 另外项目源代码仓库已经迁移到上述地址, 我刚刚更新了该主题完整的 `_config.yml`文件, 可帮你省去复制粘贴的麻烦,只需重命名和按需替换原 `_congfig.yml` 文件. have good day :)
