### ISSUE TITLE
close

### ISSUE THREAD

**Issue by perixiaowan** [ehazon/ehazon.github.io#2]
很喜欢您这个页面，也想借鉴来用下，请问能否参考您的源码么？

**Comment by Haojen** [comment]
非常感谢你能喜欢这个主题 ：），https://github.com/Haojen/hexo-theme-Anisina  这里就是源码， 有什么不懂的可以直接看下面的英文文档。

如果还有其它问题，可以直接在github上联系我
日安。

**Comment by perixiaowan** [comment]
好的，非常感谢，我先研究下，如果不懂的，再请教大牛。

**Comment by Haojen** [comment]
@perixiaowan  使用主题之前，建议你阅读 hexo 官方文档，这样在搭建过程中遇到问题时便不会一头雾水了 ：）

最后祝你如愿搭建博客成功 ！

**Comment by perixiaowan** [comment]
很感谢你的回复，其实我已经搭建了，这个是我的博客https://perixiaowan.github.io/，我想添加img文件夹，使用图片，不知这是需要配置哪个选项自动生成？还是自己手动添加这个文件夹，一直没有找到配置选项。。。还有你的标签，比如“about me”“tags”，又是如何添加的呢？

**Comment by perixiaowan** [comment]
哈哈，其实很想看看你博客的源码，不知道是否方便？

**Comment by perixiaowan** [comment]
哈哈，其实很想看看你博客的源码，不知道是否方便？

**Comment by perixiaowan** [comment]
我现在手动添加上了，你的about中html是自己写的代码吧，照葫芦画瓢，自己改一下用了，非常感谢

**Comment by Haojen** [comment]
@perixiaowan  嗯，在 github 就能直接看到我的源代码，拿去用好啦。

**Comment by perixiaowan** [comment]
https://github.com/Haojen/haojen.github.io  不好意思啊，我还得问你，你这个是生成好的静态页面，不是源码。。。

**Comment by perixiaowan** [comment]
或者不知方便加你不？

**Comment by Haojen** [comment]
@perixiaowan  微信可以么？ 我的帐号： edenmoons
